"""empty message

Revision ID: 11288927b825
Revises: 95ecfa69343
Create Date: 2015-09-20 16:30:45.618311

"""

# revision identifiers, used by Alembic.
revision = '11288927b825'
down_revision = '95ecfa69343'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_image', sa.Column('data_full', sa.LargeBinary(), nullable=True))
    op.add_column('document_image', sa.Column('data_large', sa.LargeBinary(), nullable=True))
    op.add_column('document_image', sa.Column('data_small', sa.LargeBinary(), nullable=True))
    op.drop_column('document_image', 'data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_image', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('document_image', 'data_small')
    op.drop_column('document_image', 'data_large')
    op.drop_column('document_image', 'data_full')
    ### end Alembic commands ###
