"""empty message

Revision ID: 1195cd0c81ae
Revises: 3bd5b65fcb24
Create Date: 2015-10-05 11:58:37.028602

"""

# revision identifiers, used by Alembic.
revision = '1195cd0c81ae'
down_revision = '3bd5b65fcb24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('has_screening_yn', sa.String(length=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'has_screening_yn')
    ### end Alembic commands ###
