"""empty message

Revision ID: 15658b029b4e
Revises: 2fb3c0e433f7
Create Date: 2015-10-05 16:55:58.892799

"""

# revision identifiers, used by Alembic.
revision = '15658b029b4e'
down_revision = '2fb3c0e433f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
