"""empty message

Revision ID: 1574385205f0
Revises: ae6038fc18d
Create Date: 2015-10-29 20:31:47.116373

"""

# revision identifiers, used by Alembic.
revision = '1574385205f0'
down_revision = 'ae6038fc18d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('medical_home', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'medical_home')
    ### end Alembic commands ###
