"""empty message

Revision ID: 17e1caecd877
Revises: 4baeb7ab2359
Create Date: 2015-10-26 14:40:09.373394

"""

# revision identifiers, used by Alembic.
revision = '17e1caecd877'
down_revision = '4baeb7ab2359'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
