"""empty message

Revision ID: 1abb76769029
Revises: 764fab07c2c
Create Date: 2015-10-05 17:03:54.812838

"""

# revision identifiers, used by Alembic.
revision = '1abb76769029'
down_revision = '764fab07c2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
