"""empty message

Revision ID: 2fb3c0e433f7
Revises: None
Create Date: 2015-10-05 16:55:54.475790

"""

# revision identifiers, used by Alembic.
revision = '2fb3c0e433f7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('time_in_area', sa.String(length=16), nullable=True))
    op.drop_column('patient', 'months_living_in_area')
    op.drop_column('patient', 'years_living_in_area')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('years_living_in_area', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient', sa.Column('months_living_in_area', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('patient', 'time_in_area')
    ### end Alembic commands ###
