"""empty message

Revision ID: 30eb0bad221c
Revises: 15658b029b4e
Create Date: 2015-10-05 17:02:36.319342

"""

# revision identifiers, used by Alembic.
revision = '30eb0bad221c'
down_revision = '15658b029b4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
