"""empty message

Revision ID: 32b1fde78bc2
Revises: None
Create Date: 2015-03-23 13:20:40.172091

"""

# revision identifiers, used by Alembic.
revision = '32b1fde78bc2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('middlename', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('phonenumber1', sa.String(length=32), nullable=True),
    sa.Column('phonenumber2', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    ### end Alembic commands ###
