"""empty message

Revision ID: 3f1fecf4ecc8
Revises: None
Create Date: 2015-09-23 13:33:53.079410

"""

# revision identifiers, used by Alembic.
revision = '3f1fecf4ecc8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_last_modified_by_id', 'address', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'address', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'app_user', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'app_user', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'document_image', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'document_image', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'emergency_contact', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'emergency_contact', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'employer', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'employer', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'household_member', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'household_member', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'income_source', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'income_source', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'patient', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'patient', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'patient_referral', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'patient_referral', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'patient_screening_result', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'patient_screening_result', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'phone_number', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'phone_number', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'role', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'role', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'roles_users', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'roles_users', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'service', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'service', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'service_location', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'service_location', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'service_referral_email', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'service_referral_email', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'sliding_scale', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'sliding_scale', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'sliding_scale_fee', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'sliding_scale_fee', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'unsaved_form', 'app_user', ['last_modified_by_id'], ['id'])
    op.create_foreign_key('fk_created_by_id', 'unsaved_form', 'app_user', ['created_by_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_created_by_id', 'unsaved_form', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'unsaved_form', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'sliding_scale_fee', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'sliding_scale_fee', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'sliding_scale', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'sliding_scale', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'service_referral_email', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'service_referral_email', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'service_location', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'service_location', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'service', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'service', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'roles_users', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'roles_users', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'role', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'role', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'phone_number', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'phone_number', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'patient_screening_result', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'patient_screening_result', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'patient_referral', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'patient_referral', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'patient', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'patient', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'income_source', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'income_source', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'household_member', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'household_member', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'employer', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'employer', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'emergency_contact', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'emergency_contact', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'document_image', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'document_image', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'app_user', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'app_user', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'address', type_='foreignkey')
    op.drop_constraint('fk_last_modified_by_id', 'address', type_='foreignkey')
    ### end Alembic commands ###
