"""empty message

Revision ID: 455d4e8cc28
Revises: 1abb76769029
Create Date: 2015-10-05 17:08:47.337911

"""

# revision identifiers, used by Alembic.
revision = '455d4e8cc28'
down_revision = '1abb76769029'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'spouse_years_at_current_employer')
    op.drop_column('patient', 'years_at_current_employer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('years_at_current_employer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient', sa.Column('spouse_years_at_current_employer', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
