"""empty message

Revision ID: 4baeb7ab2359
Revises: 232a843e636b
Create Date: 2015-10-26 14:38:43.372255

"""

# revision identifiers, used by Alembic.
revision = '4baeb7ab2359'
down_revision = '232a843e636b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_created_by_id', 'patient_referral_comment', 'app_user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_last_modified_by_id', 'patient_referral_comment', 'app_user', ['last_modified_by_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_last_modified_by_id', 'patient_referral_comment', type_='foreignkey')
    op.drop_constraint('fk_created_by_id', 'patient_referral_comment', type_='foreignkey')
    ### end Alembic commands ###
