"""empty message

Revision ID: 52b5f631cb70
Revises: 1bc4f7a254d1
Create Date: 2015-10-05 17:16:51.141920

"""

# revision identifiers, used by Alembic.
revision = '52b5f631cb70'
down_revision = '1bc4f7a254d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address_description_other', sa.String(length=64), nullable=True))
    op.add_column('phone_number', sa.Column('number_description_other', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_number', 'number_description_other')
    op.drop_column('address', 'address_description_other')
    ### end Alembic commands ###
