"""empty message

Revision ID: 570080d6f1d4
Revises: 3c8e551b9173
Create Date: 2015-04-20 11:49:47.766270

"""

# revision identifiers, used by Alembic.
revision = '570080d6f1d4'
down_revision = '3c8e551b9173'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
