"""empty message

Revision ID: 70d140e9e89
Revises: None
Create Date: 2015-04-20 11:46:05.134574

"""

# revision identifiers, used by Alembic.
revision = '70d140e9e89'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
