"""empty message

Revision ID: 764fab07c2c
Revises: 30eb0bad221c
Create Date: 2015-10-05 17:03:37.684153

"""

# revision identifiers, used by Alembic.
revision = '764fab07c2c'
down_revision = '30eb0bad221c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
