"""empty message

Revision ID: 95ecfa69343
Revises: 3f23834d9304
Create Date: 2015-09-20 12:44:20.135445

"""

# revision identifiers, used by Alembic.
revision = '95ecfa69343'
down_revision = '3f23834d9304'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_image', sa.Column('data', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_image', 'data')
    ### end Alembic commands ###
